### ISSUE TITLE
[BUG] Doesn't work with multiple remotes

### ISSUE THREAD

**Issue by jghyllebert** [tj-django/django-migration-fixer#117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug?

We're hosting our app on Heroku, to which we deploy using git. Therefore our local environments have an `origin` remote pointing to Github and a second `heroku` remote for deployments.

This `heroku` only has one branch, which is not our main/develop branch) and this creates issues when I try to fix migrations on my local machine.

### To Reproduce

1. Have a remote with multiple origins, without the main branch existing on one of the origins.
2. Run `./manage.py makemigrations --fix -b develop` (Though I suspect -b is not necessary)
3. Watch it fail

### What OS are you seeing the problem on?

linux

### Expected behavior?

I expected the command to just work.

### Relevant log output

```shell
DEBUG:git.cmd:Popen(["git", "version"], cwd=/home/jonas/Projects/hvn/hvn, universal_newlines=False, shell=null, istream=None)
DEBUG:git.cmd:Popen(["git", "version"], cwd=/home/jonas/Projects/hvn/hvn, universal_newlines=False, shell=null, istream=None)
DEBUG:git.cmd:Popen(["git", "init"], cwd=/home/jonas/Projects/hvn/hvn, universal_newlines=False, shell=null, istream=None)
DEBUG:git.cmd:Popen(["git", "cat-file", "--batch-check"], cwd=/home/jonas/Projects/hvn/hvn, universal_newlines=False, shell=null, istream=<valid stream>)
DEBUG:git.cmd:Popen(["git", "diff", "--cached", "--abbrev=40", "--full-index", "--raw"], cwd=/home/jonas/Projects/hvn/hvn, universal_newlines=False, shell=null, istream=None)
DEBUG:git.cmd:Popen(["git", "diff", "--abbrev=40", "--full-index", "--raw"], cwd=/home/jonas/Projects/hvn/hvn, universal_newlines=False, shell=null, istream=None)
DEBUG:git.cmd:Popen(["git", "fetch", "-v", "origin", "develop:develop"], cwd=/home/jonas/Projects/hvn/hvn, universal_newlines=True, shell=null, istream=None)
DEBUG:git.remote:Fetch head lines do not match lines provided via progress information
length of progress lines 2 should be equal to lines in FETCH_HEAD file 1
Will ignore extra progress lines or fetch head lines.
DEBUG:git.remote:info lines: [' = [up to date]        develop    -> develop', ' = [up to date]        develop    -> origin/develop']
DEBUG:git.remote:head info : ["fb17c22cd7c51a81166749ce165d7c3a8433ae6d\t\tbranch 'develop' of github.com:hvntravel/hvn\n"]
DEBUG:git.cmd:Popen(["git", "fetch", "-v", "heroku", "develop:develop"], cwd=/home/jonas/Projects/hvn/hvn, universal_newlines=True, shell=null, istream=None)
DEBUG:git.cmd:AutoInterrupt wait stderr: b''
Traceback (most recent call last):
  File "/home/jonas/Projects/hvn/hvn/.venv/lib/python3.8/site-packages/migration_fixer/management/commands/makemigrations.py", line 60, in handle
    super().handle(*app_labels, **options)
  File "/home/jonas/Projects/hvn/hvn/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/jonas/Projects/hvn/hvn/.venv/lib/python3.8/site-packages/django/core/management/commands/makemigrations.py", line 119, in handle
    raise CommandError(
django.core.management.base.CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0306_delete_vrmsurvey, 0306_reservation_email_comms_force_active in vr).
To fix them run 'python manage.py makemigrations --merge'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 50, in <module>
    execute_from_command_line(sys.argv)
  File "/home/jonas/Projects/hvn/hvn/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/jonas/Projects/hvn/hvn/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/jonas/Projects/hvn/hvn/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/jonas/Projects/hvn/hvn/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/jonas/Projects/hvn/hvn/.venv/lib/python3.8/site-packages/migration_fixer/utils.py", line 118, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/jonas/Projects/hvn/hvn/.venv/lib/python3.8/site-packages/migration_fixer/management/commands/makemigrations.py", line 109, in handle
    remote.fetch(
  File "/home/jonas/Projects/hvn/hvn/.venv/lib/python3.8/site-packages/git/remote.py", line 828, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress)
  File "/home/jonas/Projects/hvn/hvn/.venv/lib/python3.8/site-packages/git/remote.py", line 702, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/home/jonas/Projects/hvn/hvn/.venv/lib/python3.8/site-packages/git/cmd.py", line 447, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git fetch -v heroku develop:develop
```

### Anything else?

Heroku Documentation: https://devcenter.heroku.com/articles/git#creating-a-heroku-remote

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@jghyllebert This should be resolved in the latest release.

**Comment by jghyllebert** [comment]
@jackton1 Thanks for the quick resolution!
