### ISSUE TITLE
Support custom migrations base paths

### ISSUE THREAD

**Issue by stevelacey** [tj-django/django-migration-fixer#126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug?

The logic to determine the migrations path from the import path is flawed somehow, and doesn't account for projects with a non-standard django directory structure.

https://github.com/tj-django/django-migration-fixer/blob/main/migration_fixer/management/commands/makemigrations.py#L172-L178

### To Reproduce

Set up a project structure where migrations doesn't live `appname/migrations` away from `BASE_DIR`.

### What OS are you seeing the problem on?

linux

### Expected behavior?

The migrations directory should be loaded the same way django loads it, so it can never mismatch. If there's no better way, perhaps it should load the migrations module and inspect its modulepath.

### Relevant log output

```shell
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/app/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/app/.venv/lib/python3.8/site-packages/migration_fixer/utils.py", line 114, in wrapped
    res = handle_func(*args, **kwargs)
  File "/app/.venv/lib/python3.8/site-packages/migration_fixer/management/commands/makemigrations.py", line 247, in handle
    fix_numbered_migration(
  File "/app/.venv/lib/python3.8/site-packages/migration_fixer/utils.py", line 94, in fix_numbered_migration
    _update_migration(conflict_path, app_label, prev_migration)
  File "/app/.venv/lib/python3.8/site-packages/migration_fixer/utils.py", line 26, in _update_migration
    match = replace_regex.search(conflict_path.read_text())
  File "/usr/local/lib/python3.8/pathlib.py", line 1235, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/local/lib/python3.8/pathlib.py", line 1221, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/local/lib/python3.8/pathlib.py", line 1077, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/app/core/migrations/0020_test.py'

The path is `/app/projectname/core` not `/app/core` 👆️
```

### Anything else?

Alternatively to fixing the detection, the ability to be able to supply a path instead of `BASE_DIR` would work, the project I'm working on already has another constant that is the correct path to use in this case. The task runs successfully when I copy it into the project and fix the 2 issues I've created 🤘🏼

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@stevelacey This should be resolved in the latest release

**Comment by stevelacey** [comment]
@jackton1 thank you! 🙌🏼
